apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-management-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-backend
  template:
    metadata:
      labels:
        app: task-backend
    spec:
      containers:
      - name: task-backend
        image: task-management-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: task-backend-config
              key: mongodb_url
