apiVersion: v1
kind: Service
metadata:
  name: task-backend-service
spec:
  type: NodePort
  selector:
    app: task-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
