apiVersion: v1
kind: ConfigMap
metadata:
  name: task-backend-config
data:
  mongodb_url: "mongodb+srv://chinmayadatabase54:ctK5uRILF5Fi6Ssi@simpleprojects.axnf9.mongodb.net/taskmanagement?retryWrites=true&w=majority"
